import { defineConfig, type OxlintConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";
import tanstack from "ultracite/oxlint/tanstack";
import vitest from "ultracite/oxlint/vitest";

const vitestCompatibilityRules = {
  "vitest/max-expects": "off",
  "vitest/no-conditional-expect": "off",
  "vitest/no-standalone-expect": "off",
  "vitest/prefer-called-once": "off",
  "vitest/prefer-describe-function-title": "off",
  "vitest/prefer-each": "off",
  "vitest/prefer-expect-resolves": "off",
  "vitest/prefer-expect-type-of": "off",
  "vitest/prefer-import-in-mock": "off",
  "vitest/prefer-importing-vitest-globals": "off",
  "vitest/prefer-strict-equal": "off",
  "vitest/prefer-to-be-falsy": "off",
  "vitest/prefer-to-be-truthy": "off",
  "vitest/require-mock-type-parameters": "off",
  "vitest/require-to-throw-message": "off",
  "vitest/require-top-level-describe": "off",
  "vitest/valid-expect": "off",
} satisfies NonNullable<OxlintConfig["rules"]>;

const compatibleVitest = {
  ...vitest,
  overrides: vitest.overrides?.map((override) => ({
    ...override,
    rules: {
      ...override.rules,
      ...vitestCompatibilityRules,
    },
  })),
} satisfies OxlintConfig;

const gaiaCompatibilityRules = {
  "arrow-body-style": "off",
  "class-methods-use-this": "off",
  complexity: "off",
  curly: "off",
  "default-case": "off",
  eqeqeq: "off",
  "func-names": "off",
  "func-style": "off",
  "import/consistent-type-specifier-style": "off",
  "import/first": "off",
  "import/newline-after-import": "off",
  "jsx-a11y/label-has-associated-control": "off",
  "jsx-a11y/prefer-tag-over-role": "off",
  "max-classes-per-file": "off",
  "no-await-in-loop": "off",
  "no-bitwise": "off",
  "no-case-declarations": "off",
  "no-control-regex": "off",
  "no-eq-null": "off",
  "no-negated-condition": "off",
  "no-nested-ternary": "off",
  "no-param-reassign": "off",
  "no-plusplus": "off",
  "no-shadow": "off",
  "no-template-curly-in-string": "off",
  "no-unused-vars": "off",
  "no-use-before-define": "off",
  "no-useless-escape": "off",
  "no-useless-return": "off",
  "prefer-const": "off",
  "prefer-destructuring": "off",
  "prefer-named-capture-group": "off",
  "prefer-promise-reject-errors": "off",
  "prefer-template": "off",
  "promise/avoid-new": "off",
  "promise/param-names": "off",
  "promise/prefer-await-to-callbacks": "off",
  "promise/prefer-await-to-then": "off",
  "promise/prefer-catch": "off",
  "react-hooks/exhaustive-deps": "off",
  "react/hook-use-state": "off",
  "react/react-compiler": "off",
  "require-await": "off",
  "require-unicode-regexp": "off",
  "sort-keys": "off",
  "typescript/array-type": "off",
  "typescript/consistent-type-definitions": "off",
  "typescript/consistent-type-imports": "off",
  "typescript/method-signature-style": "off",
  "typescript/no-dynamic-delete": "off",
  "typescript/no-import-type-side-effects": "off",
  "typescript/no-invalid-void-type": "off",
  "typescript/no-non-null-assertion": "off",
  "typescript/parameter-properties": "off",
  "unicorn/catch-error-name": "off",
  "unicorn/consistent-existence-index-check": "off",
  "unicorn/consistent-function-scoping": "off",
  "unicorn/escape-case": "off",
  "unicorn/import-style": "off",
  "unicorn/no-array-for-each": "off",
  "unicorn/no-array-method-this-argument": "off",
  "unicorn/no-array-reduce": "off",
  "unicorn/no-array-reverse": "off",
  "unicorn/no-array-sort": "off",
  "unicorn/no-await-expression-member": "off",
  "unicorn/no-document-cookie": "off",
  "unicorn/no-immediate-mutation": "off",
  "unicorn/no-lonely-if": "off",
  "unicorn/no-negated-condition": "off",
  "unicorn/no-nested-ternary": "off",
  "unicorn/no-object-as-default-parameter": "off",
  "unicorn/no-useless-promise-resolve-reject": "off",
  "unicorn/no-useless-spread": "off",
  "unicorn/no-useless-switch-case": "off",
  "unicorn/no-useless-undefined": "off",
  "unicorn/numeric-separators-style": "off",
  "unicorn/prefer-add-event-listener": "off",
  "unicorn/prefer-array-find": "off",
  "unicorn/prefer-dom-node-dataset": "off",
  "unicorn/prefer-export-from": "off",
  "unicorn/prefer-import-meta-properties": "off",
  "unicorn/prefer-native-coercion-functions": "off",
  "unicorn/prefer-number-coercion": "off",
  "unicorn/prefer-response-static-json": "off",
  "unicorn/prefer-set-has": "off",
  "unicorn/prefer-single-call": "off",
  "unicorn/prefer-spread": "off",
  "unicorn/prefer-string-replace-all": "off",
  "unicorn/prefer-structured-clone": "off",
  "unicorn/prefer-ternary": "off",
  "unicorn/relative-url-style": "off",
  "unicorn/switch-case-braces": "off",
  "unicorn/text-encoding-identifier-case": "off",
} satisfies NonNullable<OxlintConfig["rules"]>;

export default defineConfig({
  extends: [core, react, tanstack, compatibleVitest],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    ".agents/skills/**",
    ".gaia/**",
  ],
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: "error",
  },
  rules: gaiaCompatibilityRules,
});
