import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { NodeHttpServer, NodeServices } from "@effect/platform-node";
import { assert, describe, layer } from "@effect/vitest";
import { codexAppServerExecutionSelection, parseHarnessEvent, parseHarnessProfileId, parseHarnessSessionId, WorkerRecoveryAction } from "@gaia/core";
import { appendEvent, appendHarnessSessionEvent, inspectRecoverableDeliveryWorktreeOwnership, loadRun, parseDeliveryProvenance, recoverWorkerSession } from "@gaia/runtime";
import { acceptFactoryRun } from "@gaia/runtime/server-workflows";
import { makeRunPaths } from "@gaia/runtime/paths";
import { makeTestHarnessProviderRegistry } from "@gaia/runtime/test-support";
import { Effect, FileSystem, Layer } from "effect";
import { HttpClient, HttpClientRequest } from "effect/unstable/http";
import { prepareDeliveryWorktree } from "../../../packages/runtime/src/git-delivery.js";
import { snapshotWorkspace, writeWorkspaceSnapshot } from "../../../packages/runtime/src/workspace-snapshot.js";
import { makeLocalGaiaServerLayer } from "./api.js";

describe("finite worker recovery HTTP lifecycle", () => {
  layer(NodeServices.layer)((it) => it.effect("continues retained Git root B to WORKER_COMPLETED and restarts without duplicate dispatch", () => Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem; const rootB = yield* fs.makeTempDirectory({ prefix: "gaia-http-b-" }); const remote = yield* fs.makeTempDirectory({ prefix: "gaia-http-remote-" }); const git = (cwd: string, ...args: string[]) => execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
    git(rootB, "init", "-b", "main"); git(rootB, "config", "user.email", "gaia@test.invalid"); git(rootB, "config", "user.name", "Gaia Test"); writeFileSync(`${rootB}/README.md`, "base\n"); git(rootB, "add", "README.md"); git(rootB, "commit", "-m", "base"); git(remote, "init", "--bare"); git(rootB, "remote", "add", "origin", remote); git(rootB, "push", "-u", "origin", "main");
    const accepted = yield* acceptFactoryRun({ delivery: { mode: "pullRequest" }, execution: codexAppServerExecutionSelection, workflow: "issueDelivery", workItem: { description: "retained", kind: "issue", title: "HTTP recovery" } }, { harnessProviderRegistry: makeTestHarnessProviderRegistry(), rootDirectory: rootB }); const paths = yield* makeRunPaths(accepted.runId, { rootDirectory: rootB }); const initial = yield* loadRun(paths); const provenance = parseDeliveryProvenance(initial.events[0]?.payload["delivery"]); if (provenance._tag === "None") throw new Error("missing provenance"); yield* prepareDeliveryWorktree({ options: { rootDirectory: rootB }, paths, provenance: provenance.value }); yield* writeWorkspaceSnapshot(paths.harnessWorkspaceBaseline, yield* snapshotWorkspace(paths.workspace));
    const before = { common: git(rootB, "rev-parse", "--path-format=absolute", "--git-common-dir"), head: git(rootB, "rev-parse", "HEAD"), inventory: git(rootB, "worktree", "list", "--porcelain"), status: git(rootB, "status", "--porcelain") }; const sessionId = `session-${accepted.runId}`; yield* appendEvent(accepted.runId, paths, { payload: { delivery: { ...provenance.value, mode: "pullRequest", stage: "delivering" } }, type: "DELIVERY_STARTED" });
    yield* appendEvent(accepted.runId, paths, { payload: { workspacePath: "workspace" }, type: "WORKSPACE_PREPARED" }); yield* appendEvent(accepted.runId, paths, { payload: { phase: "plan" }, type: "REVIEW_STARTED" }); yield* appendEvent(accepted.runId, paths, { payload: { phase: "plan", reviewPath: "plan.md", reviewerName: "reviewer", status: "approved" }, type: "REVIEW_COMPLETED" }); yield* appendEvent(accepted.runId, paths, { type: "WORKER_STARTED" });
    yield* appendHarnessSessionEvent(accepted.runId, paths, parseHarnessEvent({ capabilities: { approvals: [], fileChangeEvents: true, interruption: true, resumableSessions: true, review: false, steering: false, streamingMessages: true, structuredOutput: false, subagents: false, toolEvents: false, usageReporting: false, userQuestions: false }, kind: "sessionStarted", provider: { displayName: "Test Interactive Harness", executionModes: ["local"], providerId: "test-interactive" }, sessionId, state: "running" })); yield* appendHarnessSessionEvent(accepted.runId, paths, parseHarnessEvent({ kind: "turnStarted", sessionId, turnId: "turn-initial" })); yield* appendHarnessSessionEvent(accepted.runId, paths, parseHarnessEvent({ failure: { code: "CodexThreadSystemError", kind: "providerFailure", message: "failed", recoverable: true }, kind: "sessionFailed", sessionId })); yield* appendEvent(accepted.runId, paths, { payload: { code: "HarnessSessionFailed", message: "failed", recoverable: true, stage: "runningWorker" }, type: "RUN_FAILED" });
    const failureSequence = (yield* loadRun(paths)).events.at(-1)!.sequence; let starts = 0; const action = WorkerRecoveryAction.make({ actionId: "recover-http-1", expectedFailureSequence: failureSequence, expectedSessionId: parseHarnessSessionId(sessionId), harnessProfileId: parseHarnessProfileId("codexAppServer"), kind: "retryRecoverableWorkerFailure", model: "gpt-5.4" }); const activator = (runId: string, request: WorkerRecoveryAction) => recoverWorkerSession(runId, request, { nativeThreadId: "thread-private", rootDirectory: rootB, provider: { listModels: () => Effect.succeed([{ hidden: false, id: "gpt-5.4" }]), readThread: (threadId) => Effect.succeed({ active: false, systemError: true, threadId }), resumeThread: (threadId) => Effect.succeed({ threadId }), startTurn: () => Effect.sync(() => { starts++; return { turnId: "turn-recovery" }; }) }, validateWorkspace: () => inspectRecoverableDeliveryWorktreeOwnership({ expectedHeads: [provenance.value.baseRevision], options: { rootDirectory: rootB }, paths, provenance: provenance.value }) });
    const server = makeLocalGaiaServerLayer({ host: "127.0.0.1", pid: process.pid, rootDirectory: rootB, serverId: "srv_http_recovery", startedAt: new Date().toISOString() }, { harnessProviderRegistry: makeTestHarnessProviderRegistry(), workerRecoveryActivator: activator }, []).pipe(Layer.provideMerge(NodeHttpServer.layerTest)); const post = () => HttpClientRequest.post(`/runs/${accepted.runId}/recovery/actions`).pipe(HttpClientRequest.bodyJsonUnsafe(action), HttpClient.execute, Effect.provide(server)); const response = yield* post(); assert.strictEqual(response.status, 200); const after = yield* loadRun(paths); if (!after.events.some(({ type }) => type === "WORKER_COMPLETED")) throw new Error(after.events.map(({ type }) => type).join(",")); assert.strictEqual(starts, 1); assert.strictEqual((yield* post()).status, 200); assert.strictEqual(starts, 1); assert.deepEqual({ common: git(rootB, "rev-parse", "--path-format=absolute", "--git-common-dir"), head: git(rootB, "rev-parse", "HEAD"), inventory: git(rootB, "worktree", "list", "--porcelain"), status: git(rootB, "status", "--porcelain") }, before);
  }), 20_000));
});
